import { fetchAndCacheFreeGames, type FetchGamesResult } from '@/ai/flows/fetch-and-cache-free-games';
import { GameList } from '@/components/game-list';
import { LoadingSkeleton } from '@/components/loading-skeleton';
import { Suspense } from 'react';
import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert';
import { Terminal, Info, Database, Cloud } from 'lucide-react';
import type { Game } from '@/lib/game';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { ClearCacheButton } from '@/components/clear-cache-button';
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion"

export const maxDuration = 120; // 2 minutes

async function GamesSection() {
  let result: FetchGamesResult | null = null;
  let error: Error | null = null;
  
  try {
    result = await fetchAndCacheFreeGames('Epic Games Store,Amazon Prime Gaming,GOG,Steam');
  } catch (e) {
    console.error("Failed to fetch games:", e);
    error = e instanceof Error ? e : new Error('An unknown error occurred.');
  }

  const gamesWithData = result?.games.map((game) => ({
    name: game.title,
    platform: game.platform,
    game_link: game.dealLink,
    cover_image: game.imageURL,
    original_price: game.original_price,
    endDate: game.endDate,
    gameplay_url: game.gameplay,
  })) || [];

  const platformGames = {
    "Epic Games Store": gamesWithData.filter(g => g.platform === 'Epic Games Store'),
    "Amazon Prime Gaming": gamesWithData.filter(g => g.platform === 'Amazon Prime Gaming'),
    "GOG": gamesWithData.filter(g => g.platform === 'GOG'),
    "Steam": gamesWithData.filter(g => g.platform === 'Steam'),
  };

  return (
    <>
      <GameList initialGameData={platformGames} initialError={error?.message || null} />
      {result && <DebugInfo result={result} />}
      {error && !result && (
         <div className="container mx-auto px-4 py-8">
            <Alert variant="destructive">
              <Terminal className="h-4 w-4" />
              <AlertTitle>Failed to load games</AlertTitle>
              <AlertDescription>
                <p>There was an error fetching the latest free games:</p>
                <pre className="mt-2 whitespace-pre-wrap rounded-md bg-destructive/10 p-4 text-destructive-foreground">
                  <code>{error.message}</code>
                </pre>
              </AlertDescription>
            </Alert>
         </div>
      )}
    </>
  );
}

function DebugInfo({ result }: { result: FetchGamesResult }) {
  const { source, timestamp, initialPrompt, rawOutput, modelName } = result;
  const isCache = source === 'Cache';

  return (
    <div className="container mx-auto px-4 py-8 mt-8">
      <Accordion type="single" collapsible className="w-full">
        <AccordionItem value="item-1" className="border rounded-lg bg-card/50">
          <AccordionTrigger className="px-6 py-4 text-lg font-bold hover:no-underline">
            <div className="flex items-center gap-2">
              <Info className="h-5 w-5" />
              <span>Debug Information</span>
            </div>
          </AccordionTrigger>
          <AccordionContent>
            <Card className="border-0 shadow-none bg-transparent">
              <CardHeader className="pt-0">
                <CardTitle className="flex items-center gap-2 text-base">
                  Data Fetching Details
                </CardTitle>
              </CardHeader>
              <CardContent className="space-y-6 relative">
                <div className="flex items-start gap-4 p-4 rounded-lg bg-muted/50">
                  {isCache ? (
                    <Database className="h-6 w-6 text-primary flex-shrink-0" />
                  ) : (
                    <Cloud className="h-6 w-6 text-accent flex-shrink-0" />
                  )}
                  <div className="flex-grow">
                    <p className="font-semibold">Data Source: <span className={isCache ? 'text-primary' : 'text-accent'}>{source}</span></p>
                    <p className="text-sm text-muted-foreground">
                      {isCache
                        ? `Loaded from cache. Data from: ${new Date(timestamp).toLocaleString()}`
                        : `Fetched fresh from API at: ${new Date(timestamp).toLocaleString()}`}
                    </p>
                    <p className="text-sm text-muted-foreground mt-1">
                      Generated by: <span className="font-medium text-foreground/80">{modelName}</span>
                    </p>
                  </div>
                </div>

                <div>
                  <h3 className="font-semibold mb-2">Initial Prompt (Step 1)</h3>
                  <pre className="p-4 rounded-lg bg-muted/50 text-sm overflow-x-auto">
                    <code>{initialPrompt}</code>
                  </pre>
                </div>
                
                <div>
                  <h3 className="font-semibold mb-2">Raw AI Output</h3>
                  <pre className="p-4 rounded-lg bg-muted/50 text-sm max-h-96 overflow-auto">
                    <code>{rawOutput}</code>
                  </pre>
                </div>
                <div className="opacity-0">
                    <ClearCacheButton />
                </div>
              </CardContent>
            </Card>
          </AccordionContent>
        </AccordionItem>
      </Accordion>
    </div>
  );
}


function LoadingGrid() {
  return (
    <div className="grid grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">
      {Array.from({ length: 4 }).map((_, i) => (
        <LoadingSkeleton key={i} />
      ))}
    </div>
  );
}

export default function Home() {
  return (
    <main className="min-h-screen bg-background">
      <Suspense fallback={<LoadingGrid />}>
        <GamesSection />
      </Suspense>
    </main>
  );
}
