'use client';

import type { FetchGamesResult } from '@/ai/flows/fetch-and-cache-free-games';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { ClearCacheButton } from '@/components/clear-cache-button';
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion"
import { Info, Database, Cloud } from 'lucide-react';


type DebugInfoProps = {
    result: Omit<FetchGamesResult, 'games'>
}

export function DebugInfo({ result }: DebugInfoProps ) {
  const { source, timestamp, initialPrompt, rawOutput, modelName } = result;
  const isCache = source === 'Cache';

  return (
    <div className="container mx-auto px-4 py-8 mt-8">
      <Accordion type="single" collapsible className="w-full">
        <AccordionItem value="item-1" className="border rounded-lg bg-card/50">
          <AccordionTrigger className="px-6 py-4 text-lg font-bold hover:no-underline">
            <div className="flex items-center gap-2">
              <Info className="h-5 w-5" />
              <span>Debug Information</span>
            </div>
          </AccordionTrigger>
          <AccordionContent>
            <Card className="border-0 shadow-none bg-transparent">
              <CardHeader className="pt-0">
                <CardTitle className="flex items-center gap-2 text-base">
                  Data Fetching Details
                </CardTitle>
              </CardHeader>
              <CardContent className="space-y-6 relative">
                <div className="flex items-start gap-4 p-4 rounded-lg bg-muted/50">
                  {isCache ? (
                    <Database className="h-6 w-6 text-primary flex-shrink-0" />
                  ) : (
                    <Cloud className="h-6 w-6 text-accent flex-shrink-0" />
                  )}
                  <div className="flex-grow">
                    <p className="font-semibold">Data Source: <span className={isCache ? 'text-primary' : 'text-accent'}>{source}</span></p>
                    <p className="text-sm text-muted-foreground">
                      {isCache
                        ? `Loaded from cache. Data from: ${new Date(timestamp).toLocaleString()}`
                        : `Fetched fresh from API at: ${new Date(timestamp).toLocaleString()}`}
                    </p>
                    <p className="text-sm text-muted-foreground mt-1">
                      Generated by: <span className="font-medium text-foreground/80">{modelName}</span>
                    </p>
                  </div>
                  <div className="absolute top-4 right-4">
                    <ClearCacheButton />
                  </div>
                </div>

                <div>
                  <h3 className="font-semibold mb-2">Initial Prompt (Step 1)</h3>
                  <pre className="p-4 rounded-lg bg-muted/50 text-sm overflow-x-auto">
                    <code>{initialPrompt}</code>
                  </pre>
                </div>
                
                <div>
                  <h3 className="font-semibold mb-2">Raw AI Output</h3>
                  <pre className="p-4 rounded-lg bg-muted/50 text-sm max-h-96 overflow-auto">
                    <code>{rawOutput}</code>
                  </pre>
                </div>
              </CardContent>
            </Card>
          </AccordionContent>
        </AccordionItem>
      </Accordion>
    </div>
  );
}